name: circleci

on: [status]
jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Run CircleCI documentation artifact redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.DEVSTATS_CIRCLECI_TOKEN }}
          artifact-path: 0/devstats.scientific-python.org/_build/html/index.html
          circleci-jobs: documentation
